// <auto-generated />
using System;
using InstitutoTriboDeDavi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstitutoTriboDeDavi.Infrastructure.Migrations
{
    [DbContext(typeof(TriboDeDaviContext))]
    [Migration("20260904010143_PoloNomeUsuarioOpcional")]
    partial class PoloNomeUsuarioOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("AnonimizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("AutorizaImagem")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AutorizaImagemEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("CPFResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("CodigoResponsavel")
                        .HasMaxLength(16)
                        .HasColumnType("VARCHAR(16)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EhAdulto")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Escola")
                        .HasColumnType("text");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<string>("FotoArquivoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR(120)")
                        .HasColumnName("Nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Parentesco")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .HasColumnType("text");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("RG")
                        .HasColumnType("text");

                    b.Property<string>("RGResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoResponsavel");

                    b.ToTable("ALUNOS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AnotacaoAtleta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Autor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("ATLETA_ANOTACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Atleta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaPeso")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("ATLETA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AvaliacaoFisica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("ATLETA_AVALIACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Aviso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("AVISO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AvisoCiente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvisoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCiente")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("AvisoId", "UsuarioLogin")
                        .IsUnique();

                    b.ToTable("AVISO_CIENTE", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.BemPatrimonial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroPatrimonio")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BEM_PATRIMONIAL", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.Atividade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Principio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenciaBiblica")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("ATIVIDADES", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.AtividadeDoBloco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtividadeId")
                        .HasColumnType("BIGINT");

                    b.Property<long>("BlocoDoPlanoId")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("BlocoDoPlanoId");

                    b.ToTable("ATIVIDADES_DO_BLOCO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.Aula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PresencaSalva")
                        .HasColumnType("boolean");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AULAS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoModelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<long>("ModeloDeAulaId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloDeAulaId");

                    b.ToTable("BLOCOS_DO_MODELO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoPlano", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<long>("PlanoDeAulaId")
                        .HasColumnType("BIGINT");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanoDeAulaId");

                    b.ToTable("BLOCOS_DO_PLANO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.DocumentoArquivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("DOCUMENTO_ARQUIVO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.ModeloDeAula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracaoTotalMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("MODELOS_DE_AULA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.OcorrenciaAluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("OCORRENCIA_ALUNO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.PlanoDeAula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AulaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DuracaoTotalMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoloId", "Turma", "DataPrevista");

                    b.ToTable("PLANOS_DE_AULA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.Presenca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<long>("AulaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstaPresente")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JustificadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("JustificativaResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PRESENCAS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.PushSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioLogin");

                    b.ToTable("PUSH_SUBSCRIPTION", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.RelatorioSalvo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Colunas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FonteId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Turma")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioLogin");

                    b.ToTable("RELATORIOS_SALVOS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.SincronizacaoHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Atualizados")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Erros")
                        .HasColumnType("text");

                    b.Property<int>("Ignorados")
                        .HasColumnType("integer");

                    b.Property<int>("Inseridos")
                        .HasColumnType("integer");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("PoloNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SINCRONIZACAO_HISTORICO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Cobranca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<long?>("ContaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MovimentacaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PagamentoData")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PagamentoForma")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("PagamentoValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PlanoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Competencia");

                    b.HasIndex("AlunoId", "Competencia");

                    b.ToTable("COBRANCA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Competicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("CategoriaPeso")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Colocacao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Finalizacoes")
                        .HasColumnType("integer");

                    b.Property<int>("Lutas")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Vitorias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("ATLETA_COMPETICAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.CompeticaoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Organizador")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("PrazoInscricao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("COMPETICAO_EVENTO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ConfiguracaoDashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("CONFIGURACAO_DASHBOARD", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ConfiguracaoDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LinhaExtra")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool>("MostrarDataGeracao")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarLogo")
                        .HasColumnType("boolean");

                    b.Property<string>("TextoRodape")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("TextosPadraoJson")
                        .HasColumnType("text");

                    b.Property<string>("TituloCabecalho")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("CONFIGURACAO_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ConfiguracaoFotoAluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("MostrarNaCarteirinha")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarNaChamada")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarNoCadastro")
                        .HasColumnType("boolean");

                    b.Property<bool>("MostrarNoResponsavel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CONFIG_FOTO_ALUNO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ContaFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Banco")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Numero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CONTA_FINANCEIRA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Doacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("DoadorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Finalidade")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("ReciboDocumentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReciboNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("DoadorId");

                    b.ToTable("DOACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Doador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("DOADOR", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.DocumentoOficial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroFormatado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Ano", "Numero")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("DOCUMENTO_OFICIAL", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.EventoCalendario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DiasAntecedencia")
                        .HasColumnType("integer");

                    b.Property<string>("EmailsNotificacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Interno")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificacaoEnviada")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notificar")
                        .HasColumnType("boolean");

                    b.Property<long?>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("EVENTO_CALENDARIO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.FotoArquivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("FOTO_ARQUIVO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.FotoTreino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArquivoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ConsentimentoConfirmado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataAula")
                        .HasColumnType("date");

                    b.Property<string>("Legenda")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfessorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Publicada");

                    b.HasIndex("PoloId", "Turma", "DataAula")
                        .IsUnique()
                        .HasFilter("\"Categoria\" = 'polo'");

                    b.ToTable("FOTO_TREINO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Graduacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FaixaAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("FaixaNova")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("Data", "PoloId");

                    b.ToTable("GRADUACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.HorarioTurma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("HoraFim")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<long>("PoloId")
                        .HasColumnType("BIGINT");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoloId");

                    b.ToTable("POLO_HORARIO_TURMA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.IndicadorAvaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliacaoFisicaId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoFisicaId");

                    b.ToTable("ATLETA_AVALIACAO_INDICADOR", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Inscricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AceitouComodato")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitouImagem")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitouLgpd")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitouTermo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<long?>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<bool>("Anonimizada")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AnonimizadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CodigoResponsavel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CpfResponsavel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataRevisao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Escola")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<string>("FotoArquivoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("JaEraAluno")
                        .HasColumnType("boolean");

                    b.Property<string>("Medicamentos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NomeAssinatura")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ObservacaoRevisao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Parentesco")
                        .HasColumnType("integer");

                    b.Property<string>("ParentescoOutro")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(6,2)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Publico")
                        .HasColumnType("integer");

                    b.Property<string>("RespostasFamiliarJson")
                        .HasColumnType("text");

                    b.Property<string>("RespostasSaudeJson")
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Rg")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RgResponsavel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Rua")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Serie")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("TemRestricaoMedica")
                        .HasColumnType("boolean");

                    b.Property<int?>("Turma")
                        .HasColumnType("integer");

                    b.Property<int?>("TurmaAnterior")
                        .HasColumnType("integer");

                    b.Property<string>("VersaoTermos")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PoloId");

                    b.HasIndex("Status", "Ano");

                    b.ToTable("INSCRICAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Lesao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("integer");

                    b.Property<string>("Local")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Recuperado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("ATLETA_LESAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Alteracoes")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("EntidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Resumo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UsuarioLogin")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("LOG_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Matricula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoEncerramento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Turma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "Ano")
                        .IsUnique();

                    b.HasIndex("Ano", "PoloId");

                    b.ToTable("MATRICULA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MatriculaFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<string>("DescontoTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DescontoValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("Inicio")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("PlanoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("PlanoId");

                    b.ToTable("MATRICULA_FINANCEIRA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MembroGovernanca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("Orgao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.ToTable("MEMBRO_GOVERNANCA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MensagemSolicitacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutorLogin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("AutorRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("SolicitacaoInternaId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoInternaId");

                    b.ToTable("SOLICITACAO_MENSAGEM", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MetaAtleta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("ATLETA_META", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MovimentacaoFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Conciliado")
                        .HasColumnType("boolean");

                    b.Property<long>("ContaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Documento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransferenciaId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("Data");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("MOVIMENTACAO_FINANCEIRA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ParticipacaoAtleta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoriaPeso")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Colocacao")
                        .HasColumnType("integer");

                    b.Property<long>("CompeticaoEventoId")
                        .HasColumnType("BIGINT");

                    b.Property<int>("Finalizacoes")
                        .HasColumnType("integer");

                    b.Property<int>("Lutas")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Vitorias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("CompeticaoEventoId");

                    b.ToTable("COMPETICAO_PARTICIPACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.PlanoMensalidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OpcoesVencimento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("OpcoesVencimento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PLANO_MENSALIDADE", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Polo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Informacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR(120)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("POLOS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.PoloFotoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequerAutorizacao")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PoloId")
                        .IsUnique();

                    b.ToTable("POLO_FOTO_CONFIG", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FormasPagamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FotoArquivoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Informacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR(128)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UsuarioId");

                    b.ToTable("REFRESH_TOKENS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.SolicitacaoInterna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("CriadoPorLogin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("CriadoPorRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DestinatarioLogin")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long?>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("PoloNome")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorLogin");

                    b.HasIndex("DestinatarioLogin");

                    b.ToTable("SOLICITACAO_INTERNA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("Avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(180)")
                        .HasColumnName("Email");

                    b.Property<int?>("Faixa")
                        .HasColumnType("integer");

                    b.Property<string>("FotoSite")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Login");

                    b.Property<bool>("MostrarNoSite")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<bool>("PermiteGraduacao")
                        .HasColumnType("boolean");

                    b.Property<long?>("PoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("PoloNome")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("Password");

                    b.Property<bool>("TotpConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR(64)");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.VariacaoProduto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("BIGINT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PRODUTO_VARIACAO", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.VideoGaleria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Url")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("VIDEO_GALERIA", (string)null);
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AnotacaoAtleta", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Atleta", null)
                        .WithMany("Anotacoes")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AvaliacaoFisica", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Atleta", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.AtividadeDoBloco", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Business.Atividade", null)
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoPlano", null)
                        .WithMany("Atividades")
                        .HasForeignKey("BlocoDoPlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoModelo", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Business.ModeloDeAula", null)
                        .WithMany("Blocos")
                        .HasForeignKey("ModeloDeAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoPlano", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Business.PlanoDeAula", null)
                        .WithMany("Blocos")
                        .HasForeignKey("PlanoDeAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Competicao", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Atleta", null)
                        .WithMany("Competicoes")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.HorarioTurma", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Polo", null)
                        .WithMany("Horarios")
                        .HasForeignKey("PoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.IndicadorAvaliacao", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.AvaliacaoFisica", null)
                        .WithMany("Indicadores")
                        .HasForeignKey("AvaliacaoFisicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Lesao", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Atleta", null)
                        .WithMany("Lesoes")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MensagemSolicitacao", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.SolicitacaoInterna", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("SolicitacaoInternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.MetaAtleta", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Atleta", null)
                        .WithMany("Metas")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.ParticipacaoAtleta", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.CompeticaoEvento", null)
                        .WithMany("Participacoes")
                        .HasForeignKey("CompeticaoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.VariacaoProduto", b =>
                {
                    b.HasOne("InstitutoTriboDeDavi.Domain.Entities.Produto", null)
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Atleta", b =>
                {
                    b.Navigation("Anotacoes");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Competicoes");

                    b.Navigation("Lesoes");

                    b.Navigation("Metas");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.AvaliacaoFisica", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.BlocoDoPlano", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.ModeloDeAula", b =>
                {
                    b.Navigation("Blocos");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Business.PlanoDeAula", b =>
                {
                    b.Navigation("Blocos");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.CompeticaoEvento", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Polo", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("InstitutoTriboDeDavi.Domain.Entities.SolicitacaoInterna", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
