<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InstitutoTriboDeDavi.Common.DataAccess\InstitutoTriboDeDavi.Common.DataAccess.csproj" />
    <ProjectReference Include="..\InstitutoTriboDeDavi.System.Domain\InstitutoTriboDeDavi.System.Domain.csproj" />
    <ProjectReference Include="..\InstitutoTriboDeDavi.System.Infra\InstitutoTriboDeDavi.System.Infra.csproj" />
  </ItemGroup>

</Project>
